<a href="https://colab.research.google.com/github/PolyGon-13/DataScience_Study/blob/main/Preprocessing/04_Category_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [63]:
df=pd.read_csv('./data/auto-mpg.csv',header=None)

df.columns=['mpg','cylinder','displacement','horsepower','weight','acceleration','model year','origin','name']

df['horsepower']=df['horsepower'].replace('?',np.nan)
df=df.dropna(subset=['horsepower'],axis=0)
df['horsepower']=df['horsepower'].astype('float')

count,bin_dividers=np.histogram(df['horsepower'],bins=3)

print(count) # 구간에 속하는 값의 개수
print(bin_dividers) # 경계값 리스트

[257 103  32]
[ 46.         107.33333333 168.66666667 230.        ]


In [64]:
bin_names=['저출력','보통출력','고출력']

df['hp_bin']=pd.cut(x=df['horsepower'], # 데이터 배열
                    bins=bin_dividers, # 경계값 리스트
                    labels=bin_names, # bin 이름
                    include_lowest=True) # 첫 경계도 포함

df[['horsepower','hp_bin']].head(15)

horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력

In [65]:
count,bin_dividers=np.histogram(df['horsepower'],bins=3)

bin_names=['저출력','보통출력','고출력']

df['hp_bin']=pd.cut(x=df['horsepower'],
                    bins=bin_dividers,
                    labels=bin_names,
                    include_lowest=True)

# 컴퓨터만 인식할 수 있도록 0과 1로만 구성되는 원핫벡터로 변환하는 과정을 원핫인코딩이라고 함
horsepower_dummies=pd.get_dummies(df['hp_bin']) # 원핫인코딩
print(horsepower_dummies.head(15))

      저출력   보통출력    고출력
0   False   True  False
1   False   True  False
2   False   True  False
3   False   True  False
4   False   True  False
5   False  False   True
6   False  False   True
7   False  False   True
8   False  False   True
9   False  False   True
10  False  False   True
11  False   True  False
12  False   True  False
13  False  False   True
14   True  False  False


In [66]:
horsepower_dummies_float=pd.get_dummies(df['hp_bin'],dtype=float)
horsepower_dummies_float.head()

저출력  보통출력  고출력
0  0.0   1.0  0.0
1  0.0   1.0  0.0
2  0.0   1.0  0.0
3  0.0   1.0  0.0
4  0.0   1.0  0.0

In [67]:
horsepower_dummies_drop=pd.get_dummies(df['hp_bin'],dtype=float,drop_first=True)
horsepower_dummies_drop.head()

보통출력  고출력
0   1.0  0.0
1   1.0  0.0
2   1.0  0.0
3   1.0  0.0
4   1.0  0.0

In [69]:
label_encoder=preprocessing.LabelEncoder() # 범주형 데이터 -> 숫자형 데이터 변환 함수
onehot_encoder=preprocessing.OneHotEncoder() # 2차원 범주형 데이터 -> 원핫벡터 변환 함수

onehot_labeled=label_encoder.fit_transform(df['hp_bin'].head(15))
print(onehot_labeled)
print(type(onehot_labeled))

onehot_reshaped=onehot_labeled.reshape(len(onehot_labeled),1) # nx1 형태로 변환 (2차원 데이터로 변환)
print(onehot_reshaped)
print(type(onehot_reshaped))

onehot_fitted=onehot_encoder.fit_transform(onehot_reshaped)
print(onehot_fitted)
print(type(onehot_fitted))

[1 1 1 1 1 0 0 0 0 0 0 1 1 0 2]
<class 'numpy.ndarray'>
[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [2]]
<class 'numpy.ndarray'>
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 2)	1.0
<class 'scipy.sparse._csr.csr_matrix'>
